config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  
 root to: "books#top"


  resources :books
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord
    validates :title, presence: true
    validates :body, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
    
        def top
        end
        
        def index
            @lists = Book.all
            @list = Book.new
        end
    
        def show
            @lists = Book.find(params[:id])
        end
        
        def create
            @lists = Book.new(book_params)
            if @lists.save
                flash[:notice] = "Book was successfully created."
                redirect_to"/books/#{@lists.id}"
            else
                flash[:alrat] = "2 errors prohibited this book from being saved:
                ・Title can't be blank
                ・Body can't be blank"
                redirect_to"/books"
            end
        end
    
        def edit
            @lists = Book.find(params[:id])
        end
    
        def update
            @lists = Book.find(params[:id])
            if @lists.update(book_params)
                flash[:notice] = "Book was successfully update."
                redirect_to"/books/#{@lists.id}"
            else
                flash[:alrat] = "1 errors prohibited this book from being saved:
                ・Title can't be blank
                ・Body can't be blank"
                render "edit"
            end
            
        end
        
        def destroy
            @lists = Book.find(params[:id])
            @lists.destroy
            redirect_to'/books'
        end
        
        private
        
        def book_params
        params.require(:book).permit(:title, :body)
        
        end
        
end

app/controllers/lists_controller.rb
class ListsController < ApplicationController
  def new
  end

  def index
  end

  def show
  end

  def edit
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/lists_helper.rb
module ListsHelper
end

app/views/books/edit.html.erb
<h1>Editting Book</h1>

<%= form_with model: @lists do |f| %>
    <div id="error_explanation">
        <h2><%= flash[:alrat] %></h2>
    </div>
    <div class="field">
        <label for="book_title">Title</label>
        <%= f.text_field :title %>

    </div>
    <div class="field">
        <label for="book_body">Body</label>
        <%= f.text_area :body %>

    </div>
    <div class="actions">
        <%= f.submit'Update Book' %>
    </div>
    <%= link_to"Show", "/books/#{@lists.id}" %> | <%= link_to"Back", "/books" %>
    
<% end %>

app/views/books/index.html.erb
<!--books#index-->
<p id="notice"></p>
<h1>Books</h1>
<table>
    <thead>
        <tr>
            <th>Title</th>
            <th>Body</th>
            <th colspan="3"></th>
        </tr>
    </thesd>
    <tbody>
        <tr><% @lists.each do |list| %>
            <td><%= list.title %></td>
            <td><%= list.body %></td>
            <td><%= link_to "Show","/books/#{list.id}" %></td>
            <td><%= link_to "Edit","/books/#{list.id}/edit" %></td>
            <td><%= link_to "Destroy","/books/#{list.id}",method: :delete ,"data-confirm" => "Are yuo sure?"%></td>
        </tr><% end %>
    </tbody>
</table>

<h2>New book</h2>
<%= form_with model: @list do |f| %>
    <div id="error_explanation">
        <h2><%= flash[:alrat] %></h2>
    </div>
    <div class="field">
        <label for="book_title">Title</label>
        <%= f.text_field :title %>
    </div>
    <div class="field">
        <label for="book_body">Body</label>
        <%= f.text_area :body %>
    </div>
    <div class="actions">
        <%= f.submit'Create Book' %>
    </div>
<% end %>

app/views/books/new.html.erb
<h1>Lists#new</h1>
<%= form_with model:books do |f| %>
<% end %>

<h4>title</h4>
<%= f.text_field :title %>

<h4>body</h4>
<%= f.text_area :body %>

app/views/books/show.html.erb
<!--Lists#show-->

<p id="notice"><%= flash[:notice] %></p>
<p><strong>Title: </strong><%= @lists.title %></p>
<p><strong>Body: </strong><%= @lists.body %></p>

<%= link_to"Edit", "/books/#{@lists.id}/edit" %> | <%= link_to"Back", "/books" %>

app/views/books/top.html.erb
<h1>ようこそ <strong>Bookers </strong>へ !</h1>

<p><strong>Bookers </strong>では、さまざまな書籍に関するあなたの意見や</p>

<p>印象を共有し交換することができます</p>

<p>
    <%= link_to'start', books_path %>
</p>

app/views/layouts/application.html.erb
<!--books#top-->
<!DOCTYPE html>
<html>
  <head>
    <style type="text/css">
      
    </style>
    <title>WebCampBackendNew</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/lists/edit.html.erb
<h1>Lists#edit</h1>
<p>Find me in app/views/lists/edit.html.erb</p>

app/views/lists/index.html.erb
<h1>Lists#index</h1>
<p>Find me in app/views/lists/index.html.erb</p>

app/views/lists/new.html.erb
<h1>Lists#new</h1>
<%= form_with model:books do |f| %>
<% end %>

<h4>title</h4>
<%= f.text_field :title %>

<h4>body</h4>
<%= f.text_area :body %>

app/views/lists/show.html.erb
<h1>Lists#show</h1>
<p>Find me in app/views/lists/show.html.erb</p>